### PR TITLE
Update credentials loading to support Code Engine the DevX way

### PR DESCRIPTION
**Pull request by youming-lin**

### CODE REVIEW

**Review by gee4vee — APPROVED** [review]

**Comment by youming-lin** [comment]
I'm stumped by why integration test is failing :(

**Review by markstur — CHANGES_REQUESTED** [review]
I think this change goes away from what the code pattern actually says it does. The old logic worked as described.

**Comment by youming-lin** [comment]
@markstur Sorry I don't quite get what you mean.

I have a guess on why the int test is failing; will be investigating that line of thought later as I'm working on some other work.

**Review by markstur — COMMENTED** [review]
I mean... If you read the README.md it has instructions for env vars. The "DevX way" is not documented and is not normal SDK user behavior. So the logic naturally gave end user specifically set env var priority and only used the service_... setting when the others were absent. You turned the devx exception into the first priority, which I think kind of messes up the code for non-devx developers.

**Comment by youming-lin** [comment]
OK, if I prioritize the `TEXT_TO_SPEECH` env vars, would that address the issue?

**Comment by youming-lin** [comment]
@markstur I've made changes to address your concern and fix int test. Can you review this?

**Review by markstur — APPROVED** [review]
thanks! Your code does read better than what I had in there (to be fair, it was supposed to be a temporary fix)

**Pull request merged**
